### ISSUE TITLE
在MovieLens-1M数据集上训练教师模型出现错误

### ISSUE THREAD

**Issue by WanliYoung** [chenyuwuxin/DAGFM#1]
您好！我按照README文档当中介绍的操作方法进行模型的训练过程中，数据集的解析和划分没有问题，但是在利用MovieLens-1M数据集训练教师模型时，报出如下错误：
raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_8_device_/job:localhost/replica:0/task:0/device:CPU:0}} Field 0 in record 0 is not a valid int32: user_id
         [[{{node DecodeCSV}}]] [Op:IteratorGetNext]
似乎是数据集当中的数据问题。不知道您当时有没有遇到过这个问题，又是如何解决的呢？谢谢！

**Comment by Ethan-TZ** [comment]
@wending0417 您好，感谢您的关注！
之前数据集中的表头应该去掉。不过没有关系，我已经修复了这个bug，您可以尝试重新按流程运行一下。
