### ISSUE TITLE
README文档当中Distillation的参数似乎写错了

### ISSUE THREAD

**Issue by WanliYoung** [chenyuwuxin/DAGFM#2]
您好！您的README文档当中对于运行Distillation过程的命令是不是写错了？
我看到的内容是：
python train.py --config_files=[dataset]_kd_dagfm.yaml --phase=teacher_training --warm_up=/Saved/[teacher_file]
这里phase应该不是teacher_training而是distillation吧？
不知道我的理解是否正确，谢谢解答！

**Comment by Ethan-TZ** [comment]
@wending0417 确实，已修改。感谢您的反馈！:)

**Comment by WanliYoung** [comment]
您好！我正在尝试复现您的论文模型，抱歉频繁打搅您。有个问题不知道您能否解答一下。在学生模型DAGFM的FeatureInteraction当中，传入的参数feature是二维（filed_num * embedding_size）呢还是三维（batch_size * field_num * embedding_size）呢？我个人的理解似乎是前者，但是后续的einsum当中ht却又是三维的下标。由于运行模型过程出现了较多的bug，所以无法自己增加断点进行测试，不知道您能否解答一下呢？谢谢！


------------------

稳定
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Tian ***@***.***&gt;;
Send time:&nbsp;Tuesday, Jan 17, 2023 10:26 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [chenyuwuxin/DAGFM] README文档当中Distillation的参数似乎写错了 (Issue #2)





 
@wending0417 确实，已修改。感谢您的反馈！:)

**Comment by Ethan-TZ** [comment]
@wending0417 没关系的~。这个feature一直是3维的，[B，F，D]

**Comment by WanliYoung** [comment]
那我理解了。非常感谢您！谢谢！


------------------

稳定
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Tian ***@***.***&gt;;
Send time:&nbsp;Tuesday, Jan 17, 2023 11:27 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [chenyuwuxin/DAGFM] README文档当中Distillation的参数似乎写错了 (Issue #2)





 
@wending0417 没关系的~。这个feature一直是3维的，[B，F，D]
